name: Render Quarto Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render Quarto Document
      run: |
        quarto render report.qmd

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rendered-html
        path: report.html