name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbformat

    - name: Build Docker image
      run: docker build -t your-project-image .

    - name: Run Quarto render in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app \
        -e QUARTO_DENO_EXTRA_OPTIONS="--v8-flags=--stack-size=8176" \
        your-project-image \
        bash -c "pip install -r requirements.txt && quarto render report.qmd"

    - name: Upload rendered document
      uses: actions/upload-artifact@v4
      with:
        name: E-Percy-Rouhaud-SWC-RECO-analysis-STD-submission
        path: report.html
